In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("crop diseases.csv", on_bad_lines="skip")
df

          Crop  Disease Severity     Location  Temperature_C  Humidity_%
0       Cotton   Blight   Medium  Balochistan             26          45
1    Sugarcane  Healthy      Low        Sindh             30          44
2        Maize  Healthy   Medium       Punjab             41          31
3    Sugarcane     Wilt   Medium          KPK             22          24
4    Sugarcane     Rust     High          KPK             42          67
..         ...      ...      ...          ...            ...         ...
495     Cotton  Healthy      Low       Punjab             22          29
496       Rice     Wilt      Low  Balochistan             30          43
497       Rice   Blight      Low  Balochistan             16          45
498  Sugarcane   Blight      Low        Sindh             20          56
499     Cotton     Wilt     High          KPK             42          73

[500 rows x 6 columns]

In [3]:
df.head(5)

        Crop  Disease Severity     Location  Temperature_C  Humidity_%
0     Cotton   Blight   Medium  Balochistan             26          45
1  Sugarcane  Healthy      Low        Sindh             30          44
2      Maize  Healthy   Medium       Punjab             41          31
3  Sugarcane     Wilt   Medium          KPK             22          24
4  Sugarcane     Rust     High          KPK             42          67

In [4]:
df.tail(2)

          Crop Disease Severity Location  Temperature_C  Humidity_%
498  Sugarcane  Blight      Low    Sindh             20          56
499     Cotton    Wilt     High      KPK             42          73

In [5]:
df.columns

Index(['Crop', 'Disease', 'Severity', 'Location', 'Temperature_C',
       'Humidity_%'],
      dtype='object')

In [6]:
df.count()

Crop             500
Disease          500
Severity         500
Location         500
Temperature_C    500
Humidity_%       500
dtype: int64

In [7]:
df.describe()

       Temperature_C  Humidity_%
count      500.00000  500.000000
mean        29.24000   53.904000
std          8.59897   21.448049
min         15.00000   20.000000
25%         22.00000   35.000000
50%         29.00000   51.000000
75%         36.25000   71.000000
max         44.00000   94.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Crop           500 non-null    object
 1   Disease        500 non-null    object
 2   Severity       500 non-null    object
 3   Location       500 non-null    object
 4   Temperature_C  500 non-null    int64
 5   Humidity_%     500 non-null    int64
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [9]:
df.shape
print(f"Number of Rows: {df.shape[0]} and Number of Columns: {df.shape[1]}")

Number of Rows: 500 and Number of Columns: 6

In [11]:
df['Crop'].unique()

array(['Cotton', 'Sugarcane', 'Maize', 'Rice', 'Potato', 'Wheat'],
      dtype=object)

In [12]:
df.nunique()

Crop              6
Disease           6
Severity          3
Location          4
Temperature_C    30
Humidity_%       75
dtype: int64

In [14]:
# df.drop('date', axis=1, inplace=True)
df = df.drop('Disease', axis=1)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Crop           500 non-null    object
 1   Severity       500 non-null    object
 2   Location       500 non-null    object
 3   Temperature_C  500 non-null    int64
 4   Humidity_%     500 non-null    int64
dtypes: int64(2), object(3)
memory usage: 19.7+ KB

In [18]:
def convertObjToInt(cols):
    for i in cols:
        data = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))    # data_LE.fit(data)
        df[i] = data_LE.transform(df[i])
        
columns = ['Crop','Severity','Location']
convertObjToInt(columns)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Crop           500 non-null    int64
 1   Severity       500 non-null    int64
 2   Location       500 non-null    int32
 3   Temperature_C  500 non-null    int64
 4   Humidity_%     500 non-null    int64
dtypes: int32(1), int64(4)
memory usage: 17.7 KB

In [21]:
X = df.drop('Crop', axis=1)   # Dependant columns / Input columns
y = df['Crop']                # Resultant columns / Output column

In [22]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.3, shuffle=False) # 80:20, 70:30, 60:40

In [23]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(350, 4) (350,)
(150, 4) (150,)

In [24]:
from sklearn.svm import SVC # Support Vector Classifier

model_svc = SVC()
model_svc.fit(train_X, train_y)

print(model_svc)

SVC()

In [25]:
model_pred_svc = model_svc.predict(test_X)
model_pred_svc

array([0, 0, 5, 0, 1, 0, 5, 1, 0, 5, 0, 1, 5, 0, 5, 5, 5, 5, 5, 5, 0, 5,
       5, 1, 5, 5, 5, 0, 0, 5, 5, 5, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 5, 0,
       0, 0, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 5,
       0, 5, 5, 5, 5, 0, 0, 5, 5, 2, 5, 0, 5, 5, 5, 5, 5, 1, 5, 5, 0, 5,
       5, 5, 5, 5, 5, 1, 5, 0, 5, 0, 5, 0, 5, 0, 0, 5, 0, 5, 5, 5, 5, 5,
       5, 5, 0, 5, 0, 5, 5, 5, 0, 5, 0, 5, 5, 1, 5, 0, 0, 5, 5, 5, 0, 0,
       5, 5, 5, 0, 5, 0, 5, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 0], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score
model_acc_svc = accuracy_score(test_y, model_pred_svc)
print(round(model_acc_svc,3)*100, "%")

12.0 %

In [27]:
import pickle
pickle.dump(model_svc, open('model_svc.pkl', 'wb'))   # Model Saving